### ISSUE TITLE
Unresolved externals error installing pyAudio on win64

### ISSUE THREAD

**Issue by Yiqing-Zhou** [intxcc/pyaudio_portaudio#11]
I followed the process https://github.com/intxcc/pyaudio_portaudio#microsoft-visual-studio-2017.
After successfully building portaudio, I got file pyaudio\portaudio-v19\build\msvc\x64\Release\portaudio.lib.
Then I ran python.exe .\setup.py install --static-link in powershell as administrator, but got errors bellow:

    Creating library build\temp.win32-3.7\Release\src\_portaudio.cp37-win32.lib and object build\temp.win32-3.7\Release\src\_portaudio.cp37-win32.exp
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_StartStream
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetStreamTime
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_IsFormatSupported
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetStreamWriteAvailable
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetVersion
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetDefaultOutputDevice
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetDefaultInputDevice
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_HostApiTypeIdToHostApiIndex
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_WriteStream
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_CloseStream
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetStreamCpuLoad
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_OpenStream
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_Terminate
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetVersionText
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_IsStreamStopped
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_Initialize
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_HostApiDeviceIndexToDeviceIndex
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_AbortStream
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetDeviceCount
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_IsStreamActive
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetErrorText
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetSampleSize
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_ReadStream
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetDeviceInfo
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetDefaultHostApi
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetHostApiInfo
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetStreamReadAvailable
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetHostApiCount
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_GetStreamInfo
    _portaudiomodule.obj : error LNK2001: unresolved external symbol _Pa_StopStream
    build\lib.win32-3.7\_portaudio.cp37-win32.pyd : fatal error LNK1120: 30 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\link.exe' failed with exit status 1120
Seems that there is something wrong with the static links.

**Comment by Yiqing-Zhou** [comment]
Sorry, it was caused by my python. I reinstalled a 64-bit python and the problem was fixed.

**Comment by intxcc** [comment]
Alright, happy that you figured it out! :)
