### ISSUE TITLE
Cannot install on windows 10 (64bit) python37 (64bit)

### ISSUE THREAD

**Issue by claudio-perrotta** [intxcc/pyaudio_portaudio#12]
Hi intxcc,
when I try to install _PyAudio-0.2.11-cp36-cp36m-win_amd64.whl_, this is the result:
```
PS C:\Windows\system32> python -m pip install "C:\Users\Claudio\Downloads\PyAudio-0.2.11-cp36-cp36m-win_amd64.whl"
PyAudio-0.2.11-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
```
Can you made another build for Python 3.7? 😃
Or can you tell me how use latest library, without recompile all?

**Comment by intxcc** [comment]
Thank you for the feedback. I'm working on a new build :)

**Comment by intxcc** [comment]
There you go: https://github.com/intxcc/pyaudio_portaudio/releases/tag/1.1.1

Let me know if it works, so I can close this issue.

**Comment by Ivan-Kouznetsov** [comment]
I just tried installing the latest build on Windows 10 with Python 3.8.5 and got the same type of error: 
**ERROR: PyAudio-0.2.11-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.**
Can you have a look at whether this project needs a new release for Python 3.8?
