### ISSUE TITLE
Cant find portaudio

### ISSUE THREAD

**Issue by buscseik** [intxcc/pyaudio_portaudio#13]
I have installed the msi installer, and tried to start recording when I have got this error message: 
ModuleNotFoundError: No module named '_portaudio'

I have python 3.6 installed.

Do I have to install portaudio separately?

**Comment by intxcc** [comment]
Hey,
which binary did you use? "PyAudio-0.2.11.win-amd64-py3.6.msi" ?

**Comment by buscseik** [comment]
Hi,

Yep, I used the "PyAudio-0.2.11.win-amd64-py3.6.msi" binary. 
Windows 10
I have Cygwin installed, but I do not use it.
I usually start python from Powershell.
And I installed with manual installation over wizard.

**Comment by intxcc** [comment]
Hmm.. the build for 3.6 is an older one. With older sources. Are you forced to use 3.6? If not please update to 3.7 and use the latest installer. That should work.

If you really really need to use 3.6 tell me and I'll look into it.
