### ISSUE TITLE
Example 'echo.py' doesn't work. unexpected keyword argument 'as_loopback'.

### ISSUE THREAD

**Issue by dmolpa** [intxcc/pyaudio_portaudio#15]
TypeError                                 Traceback (most recent call last)
<ipython-input-67-1c3b513645de> in <module>
     75                 frames_per_buffer = defaultframes,
     76                 input_device_index = device_info["index"],
---> 77                 as_loopback = useloopback)
     78 
     79 #Start Recording

c:\users\dmolp\appdata\local\programs\python\python37\lib\site-packages\pyaudio.py in open(self, *args, **kwargs)
    748         :py:func:`Stream.__init__` for parameter details.
    749 
--> 750         :returns: A new :py:class:`Stream`
    751         """
    752 

TypeError: __init__() got an unexpected keyword argument 'as_loopback'

Windows 10 Home. Python 3.7.2. Installed from PyAudio-0.2.11-cp37-cp37m-win_amd64.whl

**Comment by fornof** [comment]
is useloopback a boolean? as_loopback = True
also, is the default pyAudio being used instead of this one? 
as_loopback is a custom build afaik.

**Comment by intxcc** [comment]
Yes, as_loopback is a boolean.

So I agree, I also think the reason is, that it is trying to use the normal pyaudio instead of this custom build.

Could you please check that? The installer can be found here: https://github.com/intxcc/pyaudio_portaudio/releases

If the error persists, please let me know.

**Comment by fornof** [comment]
I just checked, I was successfully able to use the example sample and record a wav file from my speakers as a loopback WASAPI

**Comment by intxcc** [comment]
Happy to hear that!

**Comment by bluespider1973** [comment]
Thank you
