### ISSUE TITLE
32 bit whl?

### ISSUE THREAD

**Issue by drp0** [intxcc/pyaudio_portaudio#16]
Might it be possible to create a windows 32 bit whl pre-build for inclusion at [https://github.com/intxcc/pyaudio_portaudio/releases](https://github.com/intxcc/pyaudio_portaudio/releases) ?

**Comment by drp0** [comment]
Might it be possible to create a windows whl pre-build for inclusion at [https://github.com/intxcc/pyaudio_portaudio/releases]  ?

**Comment by intxcc** [comment]
Sorry, but I do not have a 32bit machine to compile this on :/
