### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by TheCapybaraClub** [intxcc/pyaudio_portaudio#17]
Can the installation instructions be improved? I do not understand how to get this code working on my machine. After msi installer, No module named 'pyaudio'.

== update ==
c:\program files\python36\include\pyconfig.h(119): warning C4005: 'MS_WIN64': macro redefinition
c:\program files\python36\include\pyconfig.h(119): note: command-line arguments:  see previous definition of 'MS_WIN64'
src/_portaudiomodule.c(29): fatal error C1083: Cannot open include file: 'portaudio.h': No such file or directory

**Comment by intxcc** [comment]
- Which Windows Version do you use? (e.g. 10 64bit)
- Which Python version are you using (3.6 I guess?)
- Also the update looks like you tried to compile it, could you tell me what you used when trying to compile?

**Comment by TheCapybaraClub** [comment]
OS Name Microsoft Windows 10 Pro
Version 10.0.17134 Build 17134

Python --version 3.7.3

I tried msi installer, the zipped static (py setup.py), and compiling... I
would think the msi installer, after progressing thought the prompts, would
just work, no?

thank you,
Adrian

**Comment by jraspiprojects** [comment]
I got the whl install to work, after uninstalling the old PyAudio: `py -3 -m pip install PyAudio-0.2.11-cp37-cp37m-win_amd64.whl`
(Win 10, Python 3.7)

**Comment by intxcc** [comment]
Its possible that this was caused by a missing include statement.
Could you try to compile it again?

**Comment by TheCapybaraClub** [comment]
Successfully installed package using MSI and WHL.

Successfully updated echo.py example for py3.7 and captured/played back audio from speakers

Thank you for the support!
