### ISSUE TITLE
Working with Python 2.7

### ISSUE THREAD

**Issue by tylercollins590** [intxcc/pyaudio_portaudio#3]
Thank you for putting this package together! 
I have had great success using this with the simple installer on 3.5. 
Could you please explain how to use this with Python 2.7? I have downloaded your standalone files (pyaudio.py, _portaudio.dll) within the standalone folder and dropped them in my project directory. I get a no module found with name _portaudio.dll. Could you please explain how to use this with 2.7. Or have you built an installer for 2.7 like you did with 3.5?
Thank you

**Comment by intxcc** [comment]
I know. this issue is old. I'm tidying up a bit right now.

I tried to build it for 2.7. Been a while since I tried it (6 months or so) But I remember vividly, that it was not possible without substantial workarounds.

If someone else figures it out, be free to comment here.
