### ISSUE TITLE
I cann't compile it on python2.7.6 + win7 64bit

### ISSUE THREAD

**Issue by GoTop** [intxcc/pyaudio_portaudio#5]
I install cygwin

then I run Cygwin64 Terminal，change directory to "pyaudio_portaudio-master\pyaudio\portaudio-v19"

type "make"

then change directory to "pyaudio_portaudio-master\pyaudio"
type "python setup.py install --static-link"

and these error occur:
> $ python setup.py install --static-link
running install
running bdist_egg
running egg_info
writing src\PyAudio.egg-info\PKG-INFO
writing top-level names to src\PyAudio.egg-info\top_level.txt
writing dependency_links to src\PyAudio.egg-info\dependency_links.txt
reading manifest file 'src\PyAudio.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.py' under directory 'test'
warning: no files found matching '*.c' under directory 'test'
warning: no directories found matching 'docs'
writing manifest file 'src\PyAudio.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building '_portaudio' extension
C:\Users\GoTop\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS-                                                                                                             /DNDEBUG -DMS_WIN64=1 -I./portaudio-v19\include/ -IE:\Python27\include -IE:\Python27\PC /Tcsrc/_portaudiomodule.c /Fobuild\temp.w                                                                                                            in-amd64-2.7\Release\src/_portaudiomodule.obj
_portaudiomodule.c
e:\python27\include\pyconfig.h(142) : warning C4005: 'MS_WIN64' : macro redefinition
        command-line arguments :  see previous definition of 'MS_WIN64'
src/_portaudiomodule.c(46) : warning C4005: 'min' : macro redefinition
        C:\Users\GoTop\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Include\stdlib.h(850) : see previous                                                                                                             definition of 'min'
src/_portaudiomodule.c(1357) : error C2059: syntax error : '{'
src/_portaudiomodule.c(1357) : warning C4013: '__typeof__' undefined; assuming extern returning int
src/_portaudiomodule.c(1357) : error C2146: syntax error : missing ';' before identifier '_b'
src/_portaudiomodule.c(1357) : error C2065: '_b' : undeclared identifier
src/_portaudiomodule.c(1357) : error C2065: '_a' : undeclared identifier
src/_portaudiomodule.c(1357) : error C2065: '_b' : undeclared identifier
src/_portaudiomodule.c(1357) : error C2065: '_a' : undeclared identifier
src/_portaudiomodule.c(1357) : error C2065: '_b' : undeclared identifier
src/_portaudiomodule.c(1357) : error C2059: syntax error : ')'
src/_portaudiomodule.c(1357) : error C2059: syntax error : ')'
src/_portaudiomodule.c(1360) : warning C4018: '<' : signed/unsigned mismatch
src/_portaudiomodule.c(1361) : error C2065: 'output_data' : undeclared identifier
src/_portaudiomodule.c(1361) : warning C4022: 'memset' : pointer mismatch for actual parameter 1
src/_portaudiomodule.c(1367) : error C2143: syntax error : missing '{' before ':'
src/_portaudiomodule.c(1367) : error C2059: syntax error : ':'
src/_portaudiomodule.c(1374) : error C2059: syntax error : 'do'
src/_portaudiomodule.c(1374) : error C2059: syntax error : 'while'
src/_portaudiomodule.c(1375) : error C2059: syntax error : 'do'
src/_portaudiomodule.c(1375) : error C2059: syntax error : 'while'
src/_portaudiomodule.c(1376) : error C2059: syntax error : 'do'
src/_portaudiomodule.c(1376) : error C2059: syntax error : 'while'
src/_portaudiomodule.c(1378) : error C2371: 'PyGILState_Release' : redefinition; different basic types
        e:\python27\include\pystate.h(170) : see declaration of 'PyGILState_Release'
src/_portaudiomodule.c(1379) : error C2059: syntax error : 'return'
src/_portaudiomodule.c(1380) : error C2059: syntax error : '}'
error: command '"C:\Users\GoTop\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe"' failed wi                                                                                                            th exit status 2

**Comment by intxcc** [comment]
Hey,

you seem to try compiling with the VC compiler:

> C:\Users\GoTop\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe

When compiling the code as is, it's only tested on cygwin. Though there is a Windows Native build right here: https://github.com/intxcc/pyaudio_portaudio/releases/tag/1.0c
