### ISSUE TITLE
Cannot install on windows 10 (64bit) python36

### ISSUE THREAD

**Issue by camillake** [intxcc/pyaudio_portaudio#6]
Hi,
I just download  x86_64_python3.tar.gz.
Errors message is as below:
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\xx\appdata\local\programs\python\python36\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xx\\AppData\\Local\\Temp\\pip-229ndf1p-build\\setup.py'

Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxx\AppData\Local\Temp\pip-229ndf1p-build\

**Comment by intxcc** [comment]
Hello,

I updated the release to now include *.whl distributions. You can install them with "pip install \<filename\>". That should solve this problem.
