### ISSUE TITLE
Cannot install on windows 10 (64bit) python36 (64bit)

### ISSUE THREAD

**Issue by camillake** [intxcc/pyaudio_portaudio#7]
Hi intxcc,
PyAudio-0.2.11.cygwin-2.10.0-x86_64-py3.6.whl is not a supported wheel on this Win10 (64bit).
I think PyAudio-0.2.11-cp36-cp36m-win_amd64.whl might work.

**Comment by intxcc** [comment]
Are you trying to install it with the normal cmd or PowerShell on windows? The wheels are only for cygwin. The PyAudio-0.2.11.win-amd64-py3.6.msi should work in your case though.

**Comment by camillake** [comment]
Hi intxcc,

Is it possible to use  "pip install" in cmd on Windows ?

**Comment by intxcc** [comment]
Yes, that is possible.

I just made another build "PyAudio-0.2.11-cp36-cp36m-win_amd64.whl" hopefully that will work for you.
